ALTER SESSION SET CONTAINER = orclpdb1;

WHENEVER SQLERROR CONTINUE;

BEGIN
  EXECUTE IMMEDIATE 'DROP USER TickLy CASCADE';
EXCEPTION
  WHEN OTHERS THEN
    NULL;
END;
/

CREATE USER TickLy IDENTIFIED BY "itdev123"
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP;

GRANT CONNECT, RESOURCE, CREATE SESSION, CREATE TABLE, CREATE VIEW, 
       CREATE PROCEDURE, CREATE SEQUENCE, CREATE TRIGGER, CREATE SYNONYM, 
       CREATE MATERIALIZED VIEW, CREATE DATABASE LINK, CREATE ANY DIRECTORY TO TickLy;

GRANT QUERY REWRITE, GLOBAL QUERY REWRITE TO TickLy;

ALTER USER TickLy QUOTA UNLIMITED ON USERS;

COMMIT;