ALTER SESSION SET CONTAINER = PDB4;

CREATE PUBLIC DATABASE LINK LINK_SV1
CONNECT TO TICKLY IDENTIFIED BY "itdev123"
USING '//10.80.0.40:1521/PDB1';

CREATE PUBLIC DATABASE LINK LINK_SV2
CONNECT TO TICKLY IDENTIFIED BY "itdev123"
USING '//oracle-sv2:1523/PDB2';

CREATE PUBLIC DATABASE LINK LINK_SV3
CONNECT TO TICKLY IDENTIFIED BY "itdev123"
USING '//oracle-sv3:1521/PDB3';
