SAVEPOINT start_transaction;

CREATE TABLE PACIENT (
    ID NUMBER(10) PRIMARY KEY,
    Nume VARCHAR2(50) NOT NULL,
    Prenume VARCHAR2(50) NOT NULL,
    CNP VARCHAR2(13) NOT NULL,
    Adresa VARCHAR2(200) NOT NULL,
    Telefon VARCHAR2(15) NOT NULL,
    Email VARCHAR2(100) NOT NULL,
    DataNasterii DATE NOT NULL,
    Sex CHAR(1) NOT NULL,
    GrupaSanguina VARCHAR2(3) NOT NULL,
    DataInregistrarii TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    
    -- Unique constraints
    CONSTRAINT UQ_PACIENT_CNP UNIQUE (CNP),
    CONSTRAINT UQ_PACIENT_TELEFON UNIQUE (Telefon),
    CONSTRAINT UQ_PACIENT_EMAIL UNIQUE (Email),
    
    -- Check constraints
    CONSTRAINT CHK_PACIENT_CNP CHECK (REGEXP_LIKE(CNP, '^[1-9][0-9]{12}$')),
    CONSTRAINT CHK_PACIENT_TELEFON CHECK (REGEXP_LIKE(Telefon, '^07[0-9]{8}$')),
    CONSTRAINT CHK_PACIENT_EMAIL CHECK (REGEXP_LIKE(Email, '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$')),
    CONSTRAINT CHK_PACIENT_SEX CHECK (Sex IN ('M', 'F')),
    CONSTRAINT CHK_PACIENT_GRUPA_SANGUINA CHECK (GrupaSanguina IN ('A+', 'A-', 'B+', 'B-', 'AB+', 'AB-', 'O+', 'O-'))
);

CREATE TABLE SPECIALIZARE (
    ID NUMBER(10) PRIMARY KEY,
    Denumire VARCHAR2(100) NOT NULL,
    Descriere VARCHAR2(500) NOT NULL,
    Nivel VARCHAR2(50) NOT NULL,
    CodSpecializare VARCHAR2(20) NOT NULL,
    
    -- Unique constraint
    CONSTRAINT UQ_SPECIALIZARE_COD UNIQUE (CodSpecializare)
);

CREATE TABLE DEPARTAMENT (
    ID NUMBER(10) PRIMARY KEY,
    NumeDepartament VARCHAR2(100) NOT NULL,
    Locatie VARCHAR2(100) NOT NULL,
    IdSefDepartament NUMBER(10),
    BugetAlocat NUMBER(12,2) NOT NULL,
    NrPaturi NUMBER(4) NOT NULL,
    TelefonContact VARCHAR2(15) NOT NULL,
    
    -- Unique constraint
    CONSTRAINT UQ_DEPARTAMENT_TELEFON UNIQUE (TelefonContact),
    
    -- Check constraints
    CONSTRAINT CHK_DEPARTAMENT_BUGET CHECK (BugetAlocat > 0),
    CONSTRAINT CHK_DEPARTAMENT_PATURI CHECK (NrPaturi > 0),
    CONSTRAINT CHK_DEPARTAMENT_TELEFON CHECK (REGEXP_LIKE(TelefonContact, '^07[0-9]{8}$'))
);

CREATE TABLE MEDIC (
    ID NUMBER(10) PRIMARY KEY,
    Nume VARCHAR2(50) NOT NULL,
    Prenume VARCHAR2(50) NOT NULL,
    CNP VARCHAR2(13) NOT NULL,
    Telefon VARCHAR2(15) NOT NULL,
    Email VARCHAR2(100) NOT NULL,
    DataAngajare DATE NOT NULL,
    GradProfesional VARCHAR2(50) NOT NULL,
    NrLicenta VARCHAR2(20) NOT NULL,
    IdDepartament NUMBER(10) NOT NULL,

    -- Unique constraints
    CONSTRAINT UQ_MEDIC_CNP UNIQUE (CNP),
    CONSTRAINT UQ_MEDIC_TELEFON UNIQUE (Telefon),
    CONSTRAINT UQ_MEDIC_EMAIL UNIQUE (Email),
    CONSTRAINT UQ_MEDIC_NR_LICENTA UNIQUE (NrLicenta),

    -- Foreign key constraint
    CONSTRAINT FK_MEDIC_DEPARTAMENT FOREIGN KEY (IdDepartament)
        REFERENCES DEPARTAMENT(ID),

    -- Check constraints
    CONSTRAINT CHK_MEDIC_CNP CHECK (REGEXP_LIKE(CNP, '^[1-9][0-9]{12}$')),
    CONSTRAINT CHK_MEDIC_TELEFON CHECK (REGEXP_LIKE(Telefon, '^07[0-9]{8}$')),
    CONSTRAINT CHK_MEDIC_EMAIL CHECK (REGEXP_LIKE(Email, '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$'))
);

ALTER TABLE DEPARTAMENT
ADD CONSTRAINT FK_DEPARTAMENT_SEF FOREIGN KEY (IdSefDepartament) 
    REFERENCES MEDIC(ID);

CREATE TABLE PROGRAMARE (
    ID NUMBER(10) PRIMARY KEY,
    IDPacient NUMBER(10) NOT NULL,
    IDMedic NUMBER(10) NOT NULL,
    DataProgramare DATE NOT NULL,
    OraProgramare VARCHAR2(5) NOT NULL,
    Status VARCHAR2(20) NOT NULL,
    MotivPrezentare VARCHAR2(500) NOT NULL,
    Observatii VARCHAR2(500),

    -- Foreign key constraints
    CONSTRAINT FK_PROGRAMARE_PACIENT FOREIGN KEY (IDPacient)
        REFERENCES PACIENT(ID),
    CONSTRAINT FK_PROGRAMARE_MEDIC FOREIGN KEY (IDMedic)
        REFERENCES MEDIC(ID),

    -- Check constraints
    CONSTRAINT CHK_PROGRAMARE_ORA CHECK (REGEXP_LIKE(OraProgramare, '^([0-1][0-9]|2[0-3]):[0-5][0-9]$')),
    CONSTRAINT CHK_PROGRAMARE_STATUS CHECK (Status IN ('Programata', 'Anulata', 'Realizata'))
);

CREATE TABLE ALERGIE (
    ID NUMBER(10) PRIMARY KEY,
    Denumire VARCHAR2(100) NOT NULL,
    Descriere VARCHAR2(500) NOT NULL,
    TipAlergie VARCHAR2(50) NOT NULL,
    CodMedical VARCHAR2(20) NOT NULL,
    
    -- Unique constraint
    CONSTRAINT UQ_ALERGIE_COD_MEDICAL UNIQUE (CodMedical)
);

CREATE TABLE MEDIC_SPECIALIZARE (
    IDMedic NUMBER(10),
    IDSpecializare NUMBER(10),
    DataObtinere DATE NOT NULL,
    CertificatNr VARCHAR2(20) NOT NULL,

    -- Primary key constraint (composite)
    CONSTRAINT PK_MEDIC_SPECIALIZARE PRIMARY KEY (IDMedic, IDSpecializare),

    -- Foreign key constraints
    CONSTRAINT FK_MEDIC_SPECIALIZARE_MEDIC FOREIGN KEY (IDMedic)
        REFERENCES MEDIC(ID),
    CONSTRAINT FK_MEDIC_SPECIALIZARE_SPECIALIZARE FOREIGN KEY (IDSpecializare)
        REFERENCES SPECIALIZARE(ID),

    -- Unique constraint
    CONSTRAINT UQ_MEDIC_SPECIALIZARE_CERTIFICAT UNIQUE (CertificatNr)
);

CREATE TABLE PACIENT_ALERGIE (
    IDPacient NUMBER(10),
    IDAlergie NUMBER(10),
    DataDiagnostic DATE NOT NULL,
    Observatii VARCHAR2(500),
    Severitate NUMBER(1) NOT NULL,
    
    -- Primary key constraint (composite)
    CONSTRAINT PK_PACIENT_ALERGIE PRIMARY KEY (IDPacient, IDAlergie),
    
    -- Foreign key constraints
    CONSTRAINT FK_PACIENT_ALERGIE_PACIENT FOREIGN KEY (IDPacient) 
        REFERENCES PACIENT(ID),
    CONSTRAINT FK_PACIENT_ALERGIE_ALERGIE FOREIGN KEY (IDAlergie) 
        REFERENCES ALERGIE(ID),
    
    -- Check constraint
    CONSTRAINT CHK_PACIENT_ALERGIE_SEVERITATE CHECK (Severitate IN (1, 2, 3, 4, 5))
);

CREATE TABLE CONSULTATIE (
    ID NUMBER(10) PRIMARY KEY,
    IDProgramare NUMBER(10) NOT NULL,
    DataConsultatie TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    Diagnostic VARCHAR2(500) NOT NULL,
    Observatii VARCHAR2(500),
    Recomandari VARCHAR2(500),
    Urgenta NUMBER(1) NOT NULL,

    -- Foreign key constraint
    CONSTRAINT FK_CONSULTATIE_PROGRAMARE FOREIGN KEY (IDProgramare)
        REFERENCES PROGRAMARE(ID),

    -- Check constraint
    CONSTRAINT CHK_CONSULTATIE_URGENTA CHECK (Urgenta IN (1, 2, 3, 4, 5))
);

CREATE TABLE RETETA (
    ID NUMBER(10) PRIMARY KEY,
    IDConsultatie NUMBER(10) NOT NULL,
    DataPrescriere TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    DataExpirare TIMESTAMP NOT NULL,
    Observatii VARCHAR2(500),
    Status VARCHAR2(20) NOT NULL,
    CodUnic VARCHAR2(20) NOT NULL,
    
    -- Foreign key constraint
    CONSTRAINT FK_RETETA_CONSULTATIE FOREIGN KEY (IDConsultatie) 
        REFERENCES CONSULTATIE(ID),
    
    -- Unique constraint
    CONSTRAINT UQ_RETETA_COD_UNIC UNIQUE (CodUnic),
    
    -- Check constraints
    CONSTRAINT CHK_RETETA_DATA CHECK (DataExpirare > DataPrescriere),
    CONSTRAINT CHK_RETETA_STATUS CHECK (Status IN ('In asteptare', 'In curs', 'Finalizata'))
);

CREATE TABLE MEDICAMENT (
    ID NUMBER(10) PRIMARY KEY,
    Denumire VARCHAR2(100) NOT NULL,
    SubstantaActiva VARCHAR2(200) NOT NULL,
    Concentratie VARCHAR2(50) NOT NULL,
    FormaFarmaceutica VARCHAR2(50) NOT NULL,
    Producator VARCHAR2(100) NOT NULL,
    PretUnitar NUMBER(10,2) NOT NULL,
    StocDisponibil NUMBER(10) NOT NULL,
    NecesitaReteta NUMBER(1) NOT NULL,
    
    -- Check constraints
    CONSTRAINT CHK_MEDICAMENT_CONCENTRATIE CHECK (
        REGEXP_LIKE(Concentratie, '^[0-9][0-9].*$')
    ),
    CONSTRAINT CHK_MEDICAMENT_PRET CHECK (PretUnitar > 0),
    CONSTRAINT CHK_MEDICAMENT_STOC CHECK (StocDisponibil >= 0),
    CONSTRAINT CHK_MEDICAMENT_NECESITA_RETETA CHECK (NecesitaReteta IN (0, 1))
);

CREATE TABLE RETETA_MEDICAMENT (
    IDReteta NUMBER(10),
    IDMedicament NUMBER(10),
    Cantitate NUMBER(10) NOT NULL,
    Dozaj VARCHAR2(50) NOT NULL,
    DurataTratament NUMBER(10) NOT NULL,
    InstructiuniAdministrare VARCHAR2(500) NOT NULL,
    
    -- Primary key constraint (composite)
    CONSTRAINT PK_RETETA_MEDICAMENT PRIMARY KEY (IDReteta, IDMedicament),
    
    -- Foreign key constraints
    CONSTRAINT FK_RETETA_MEDICAMENT_RETETA FOREIGN KEY (IDReteta) 
        REFERENCES RETETA(ID),
    CONSTRAINT FK_RETETA_MEDICAMENT_MEDICAMENT FOREIGN KEY (IDMedicament) 
        REFERENCES MEDICAMENT(ID),
    
    -- Check constraints
    CONSTRAINT CHK_RETETA_MEDICAMENT_CANTITATE CHECK (Cantitate > 0),
    CONSTRAINT CHK_RETETA_MEDICAMENT_DURATA CHECK (DurataTratament > 0)
);

COMMIT;