SAVEPOINT start_transaction;

CREATE SEQUENCE SEQ_PACIENT_ID
    START WITH 1000001
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE SEQUENCE SEQ_MEDIC_ID
    START WITH 2000001
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE SEQUENCE SEQ_DEPARTAMENT_ID
    START WITH 3000001
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE SEQUENCE SEQ_PROGRAMARE_ID
    START WITH 4000001
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE SEQUENCE SEQ_CONSULTATIE_ID
    START WITH 5000001
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE SEQUENCE SEQ_RETETA_ID
    START WITH 6000001
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE SEQUENCE SEQ_MEDICAMENT_ID
    START WITH 7000001
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE SEQUENCE SEQ_ALERGIE_ID
    START WITH 8000001
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE SEQUENCE SEQ_SPECIALIZARE_ID
    START WITH 9000001
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

COMMIT;