-- 1. Drop trigger
DROP TRIGGER trg_monitorizare_schema;

-- 2. Drop tabelul MESAJE 
DROP TABLE MESAJE;

-- 3. Drop package
DROP PACKAGE management_spital;

-- 4. Drop restul trigger-urilor
DROP TRIGGER TRG_PACIENT_ID;
DROP TRIGGER TRG_MEDIC_ID;
DROP TRIGGER TRG_PROGRAMARE_ID;
DROP TRIGGER TRG_CONSULTATIE_ID;
DROP TRIGGER TRG_RETETA_ID;
DROP TRIGGER TRG_MEDICAMENT_ID;
DROP TRIGGER TRG_ALERGIE_ID;
DROP TRIGGER TRG_SPECIALIZARE_ID;
DROP TRIGGER TRG_DEPARTAMENT_ID;
DROP TRIGGER TRG_RETETA_UNIQUE_CONSULTATIE;
DROP TRIGGER TRG_CONSULTATIE_UNIQUE_PROGRAMARE;
DROP TRIGGER TRG_RETETA_MEDICAMENT_STOC;
DROP TRIGGER TRG_RETETA_MEDICAMENT_UPDATE_STOC;
DROP TRIGGER TRG_PACIENT_DATA_NASTERII;
DROP TRIGGER TRG_MEDIC_DATA_ANGAJARE;
DROP TRIGGER TRG_PROGRAMARE_DATA;
DROP TRIGGER TRG_MEDIC_SPECIALIZARE_DATA;
DROP TRIGGER TRG_PACIENT_ALERGIE_DATA;
DROP TRIGGER TRG_CONSULTATIE_DATA;

-- 5. Drop tabele asociative
DROP TABLE RETETA_MEDICAMENT;
DROP TABLE PACIENT_ALERGIE;
DROP TABLE MEDIC_SPECIALIZARE;

-- 6. Drop tabele cu foreign keys
DROP TABLE RETETA;
DROP TABLE CONSULTATIE;
DROP TABLE PROGRAMARE;

-- 7. Drop tabele principale
ALTER TABLE DEPARTAMENT DROP CONSTRAINT FK_DEPARTAMENT_SEF;
DROP TABLE MEDIC;
DROP TABLE DEPARTAMENT;
DROP TABLE PACIENT;
DROP TABLE SPECIALIZARE;
DROP TABLE ALERGIE;
DROP TABLE MEDICAMENT;

-- 8. Drop secvente
DROP SEQUENCE SEQ_PACIENT_ID;
DROP SEQUENCE SEQ_MEDIC_ID;
DROP SEQUENCE SEQ_DEPARTAMENT_ID;
DROP SEQUENCE SEQ_PROGRAMARE_ID;
DROP SEQUENCE SEQ_CONSULTATIE_ID;
DROP SEQUENCE SEQ_RETETA_ID;
DROP SEQUENCE SEQ_MEDICAMENT_ID;
DROP SEQUENCE SEQ_ALERGIE_ID;
DROP SEQUENCE SEQ_SPECIALIZARE_ID;
DROP SEQUENCE SEQ_MESAJE;