ALTER SESSION SET CONTAINER = PDB2;

CREATE PUBLIC DATABASE LINK LINK_SV1
CONNECT TO TICKLY IDENTIFIED BY "itdev123"
USING '//10.80.0.40:1521/PDB1';

CREATE PUBLIC DATABASE LINK LINK_SV3
CONNECT TO TICKLY IDENTIFIED BY "itdev123"
USING '//oracle-sv3:1521/PDB3';

CREATE PUBLIC DATABASE LINK LINK_SV4
CONNECT TO TICKLY IDENTIFIED BY "itdev123"
USING '//oracle-sv4:1521/PDB4';
